// Demo / test fixtures. The /admin/seed-fakes endpoint creates these as
// real User + Profile rows so the admin can swipe on a varied deck during
// testing. The cast covers every userType, several stages, and locations
// spread across continents so distance/geo filters can be exercised.

export const FAKE_PASSWORD = 'test1234';

export const FAKE_USERS = [
  {
    email: 'avery.test@businesstinder.test',
    fullName: 'Avery Chen',
    headline: 'Technical co-founder, ex-Stripe',
    userType: 'cofounder_search',
    stage: 'mvp',
    industries: ['AI', 'DevTools'],
    skills: ['Engineering', 'Product'],
    location: 'San Francisco',
    remoteOk: true,
    lookingFor: ['cofounder', 'investors'],
    bio: 'Building AI-native dev tooling. Looking for a hustler co-founder to balance my engineering depth.',
    commitment: 'full_time',
    pastCompanies: ['Stripe', 'Anthropic'],
    promptIds: ['building', 'best_with'],
    promptAnswers: [
      'A coding agent that pairs with you live in your editor.',
      'People who ship before they polish.',
    ],
  },
  {
    email: 'jamie.test@businesstinder.test',
    fullName: 'Jamie Rivera',
    headline: 'Solo founder · FinTech for LATAM',
    userType: 'founder',
    stage: 'live',
    industries: ['FinTech'],
    skills: ['Product', 'Domain expert'],
    location: 'Mexico City',
    remoteOk: false,
    lookingFor: ['hires', 'investors'],
    bio: 'Building remittance rails for the Mexico–US corridor. $40k MRR, growing 20%/mo.',
    commitment: 'full_time',
    pastCompanies: ['Kavak'],
    promptIds: ['first_pilot', 'one_year_plan'],
    promptAnswers: [
      'Any LATAM gig worker network with weekly USD payouts.',
      'Cross $1M ARR and close a $3M seed round.',
    ],
  },
  {
    email: 'sam.test@businesstinder.test',
    fullName: 'Sam Park',
    headline: 'GP @ HiveCapital · pre-seed checks $100k–$500k',
    userType: 'investor',
    stage: 'scaling',
    industries: ['B2B SaaS', 'AI'],
    skills: ['Capital'],
    location: 'New York',
    remoteOk: true,
    lookingFor: ['networking'],
    bio: 'Pre-seed B2B SaaS and AI infra. Ex-VP product @ Datadog. Always happy to do office hours.',
    commitment: 'part_time',
    pastCompanies: ['Datadog'],
    promptIds: ['industry_bet'],
    promptAnswers: ['Most of the AI infra winners will be vertical, not horizontal.'],
  },
  {
    email: 'rohan.test@businesstinder.test',
    fullName: 'Rohan Patel',
    headline: 'Founding GTM hire, looking for a seed B2B SaaS to join',
    userType: 'operator',
    stage: 'idea',
    industries: ['B2B SaaS'],
    skills: ['Sales', 'Ops'],
    location: 'Berlin',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'Closed $8M ARR at Plausible. Want to join a B2B SaaS team as founding GTM and earn into the cap table.',
    commitment: 'full_time',
    pastCompanies: ['Plausible'],
    promptIds: ['skill_to_hire', 'shipped'],
    promptAnswers: [
      'A pricing analyst who lives in spreadsheets.',
      'A self-serve onboarding flow that 5×ʼd Plausible activations.',
    ],
  },
  {
    email: 'maya.test@businesstinder.test',
    fullName: 'Maya Singh',
    headline: 'Designer-founder · consumer health',
    userType: 'founder',
    stage: 'mvp',
    industries: ['HealthTech', 'Consumer'],
    skills: ['Design', 'Product'],
    location: 'London',
    remoteOk: true,
    lookingFor: ['cofounder', 'advisors'],
    bio: 'Reimagining women\'s health from the ground up. Need a clinical co-founder.',
    commitment: 'full_time',
    pastCompanies: ['Babylon Health'],
    promptIds: ['wrong_about', 'dream_advisor'],
    promptAnswers: [
      'Consumer health is not won by another tracking app.',
      'A clinician who has run their own pilot.',
    ],
  },
  {
    email: 'dom.test@businesstinder.test',
    fullName: 'Dom Hartmann',
    headline: 'Climate-tech advisor · ex-Tesla supply chain',
    userType: 'advisor',
    stage: 'scaling',
    industries: ['Climate'],
    skills: ['Domain expert', 'Ops'],
    location: 'Berlin',
    remoteOk: true,
    lookingFor: ['networking', 'partnerships'],
    bio: 'Advising climate-tech founders on hardware supply chain. 12 years inside Tesla & Northvolt.',
    commitment: 'part_time',
    pastCompanies: ['Tesla', 'Northvolt'],
    promptIds: ['learned_hard_way'],
    promptAnswers: ['Battery factories are 10× harder than the spreadsheet says.'],
  },
  {
    email: 'ying.test@businesstinder.test',
    fullName: 'Ying Zhao',
    headline: 'Marketplace founder · $1.2M ARR, hiring head of growth',
    userType: 'founder',
    stage: 'revenue',
    industries: ['Marketplace', 'Consumer'],
    skills: ['Product', 'Marketing'],
    location: 'Singapore',
    remoteOk: false,
    lookingFor: ['hires', 'partnerships'],
    bio: 'Two-sided marketplace for tutoring in SEA. $1.2M ARR, 18 months in.',
    commitment: 'full_time',
    pastCompanies: ['Grab', 'Lazada'],
    promptIds: ['biggest_open_question'],
    promptAnswers: ['How do we move from one-region dominance to two without losing the unit economics?'],
  },
  {
    email: 'noah.test@businesstinder.test',
    fullName: 'Noah Williams',
    headline: 'Web3 builder · DeFi infra · ex-OpenSea',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['Web3'],
    skills: ['Engineering'],
    location: 'Lisbon',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'Solidity dev. Looking for a non-tech co-founder with deep finance domain expertise.',
    commitment: 'full_time',
    pastCompanies: ['OpenSea'],
    promptIds: ['building'],
    promptAnswers: ['On-chain credit infrastructure for emerging-market lenders.'],
  },
  {
    email: 'priya.test@businesstinder.test',
    fullName: 'Priya Iyer',
    headline: 'PM/engineer hybrid, want to build AI agents for SMBs',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['B2B SaaS', 'AI'],
    skills: ['Product', 'Engineering'],
    location: 'San Francisco',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'PM-eng hybrid, last 4 years at Notion. Want a sales/marketing co-founder.',
    commitment: 'full_time',
    pastCompanies: ['Notion'],
    promptIds: ['one_year_plan', 'best_with'],
    promptAnswers: [
      'Have 50 paying SMBs on an AI agent for their workflows.',
      'People who do customer interviews on weekends.',
    ],
  },
  {
    email: 'lukas.test@businesstinder.test',
    fullName: 'Lukas Müller',
    headline: 'Solo founder, hiring founding engineer (Rust/Go)',
    userType: 'founder',
    stage: 'live',
    industries: ['DevTools', 'AI'],
    skills: ['Engineering'],
    location: 'Amsterdam',
    remoteOk: true,
    lookingFor: ['hires', 'customers'],
    bio: 'AI code-review tool. 50 paying teams. Looking for a founding engineer who lives in low-level code.',
    commitment: 'full_time',
    pastCompanies: ['JetBrains'],
    promptIds: ['shipped', 'side_obsession'],
    promptAnswers: [
      'A static analyzer that catches real bugs without flooding you with false positives.',
      'Trail running ultras.',
    ],
  },
  {
    email: 'yuki.test@businesstinder.test',
    fullName: 'Yuki Tanaka',
    headline: 'Robotics founder · last-mile delivery in dense cities',
    userType: 'founder',
    stage: 'scaling',
    industries: ['Robotics', 'Logistics'],
    skills: ['Engineering', 'Ops'],
    location: 'Tokyo',
    remoteOk: false,
    lookingFor: ['investors', 'hires'],
    bio: 'Sidewalk robots doing 2,000 deliveries/day in Shibuya. Raising Series A.',
    commitment: 'full_time',
    pastCompanies: ['SoftBank Robotics'],
    promptIds: ['biggest_open_question', 'one_year_plan'],
    promptAnswers: [
      'Regulation in 3 new cities at once — what breaks first?',
      'Operate in 5 cities with positive unit economics per route.',
    ],
  },
  {
    email: 'aisha.test@businesstinder.test',
    fullName: 'Aisha Bello',
    headline: 'Domain founder looking for technical co-founder · African FinTech',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['FinTech'],
    skills: ['Sales', 'Domain expert'],
    location: 'Lagos',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: '10 years in Nigerian microfinance. Want a CTO to build cross-border SMB payment rails for West Africa.',
    commitment: 'full_time',
    pastCompanies: ['Flutterwave', 'Carbon'],
    promptIds: ['building', 'best_with'],
    promptAnswers: [
      'Stripe for African SMBs that actually clears the same day.',
      'Engineers who care about latency in Lagos more than perfect Figma.',
    ],
  },
  {
    email: 'felipe.test@businesstinder.test',
    fullName: 'Felipe Costa',
    headline: 'AgriTech founder · $600k ARR, hiring sales',
    userType: 'founder',
    stage: 'revenue',
    industries: ['AgriTech', 'Climate'],
    skills: ['Product', 'Domain expert'],
    location: 'São Paulo',
    remoteOk: false,
    lookingFor: ['hires', 'investors'],
    bio: 'Satellite-driven yield forecasting for soy and corn farms in Brazil. 800 farms onboarded.',
    commitment: 'full_time',
    pastCompanies: ['Embraer', 'Solinftec'],
    promptIds: ['first_pilot', 'learned_hard_way'],
    promptAnswers: [
      'Any co-op of 50+ mid-sized farmers in Mato Grosso.',
      'Farmers will pay for accuracy, not for dashboards.',
    ],
  },
  {
    email: 'hannah.test@businesstinder.test',
    fullName: 'Hannah O\'Brien',
    headline: 'Head of Ops looking to join a Series A B2B SaaS',
    userType: 'operator',
    stage: 'scaling',
    industries: ['B2B SaaS'],
    skills: ['Ops', 'Finance'],
    location: 'Dublin',
    remoteOk: true,
    lookingFor: ['cofounder', 'networking'],
    bio: 'Built ops from 20 to 200 at Intercom. Looking for a founder who hates spreadsheets as much as I love them.',
    commitment: 'full_time',
    pastCompanies: ['Intercom', 'Workday'],
    promptIds: ['skill_to_hire', 'best_with'],
    promptAnswers: [
      'A revenue ops generalist who can build dashboards from raw SQL.',
      'Founders who actually read the board memo before the meeting.',
    ],
  },
  {
    email: 'tomas.test@businesstinder.test',
    fullName: 'Tomás Vega',
    headline: 'EdTech founder · Spanish-language coding bootcamp',
    userType: 'founder',
    stage: 'mvp',
    industries: ['EdTech', 'Consumer'],
    skills: ['Product', 'Marketing'],
    location: 'Buenos Aires',
    remoteOk: true,
    lookingFor: ['cofounder', 'investors'],
    bio: 'Spanish-first online bootcamp placing junior devs into US remote roles. 80 grads, 70% placement.',
    commitment: 'full_time',
    pastCompanies: ['Globant', 'Platzi'],
    promptIds: ['building', 'industry_bet'],
    promptAnswers: [
      'A coding school that gets paid only when the student lands a job.',
      'LATAM remote talent will be a $50B export within 10 years.',
    ],
  },
  {
    email: 'aviva.test@businesstinder.test',
    fullName: 'Aviva Roth',
    headline: 'Partner @ NorthFort · cybersecurity & defense tech',
    userType: 'investor',
    stage: 'scaling',
    industries: ['CyberSec', 'DefenseTech'],
    skills: ['Capital', 'Domain expert'],
    location: 'Tel Aviv',
    remoteOk: true,
    lookingFor: ['networking'],
    bio: 'Lead Series A and B checks in Israeli cyber/defense. Ex-Unit 8200. $5M–$15M tickets.',
    commitment: 'part_time',
    pastCompanies: ['Check Point', 'Unit 8200'],
    promptIds: ['industry_bet', 'wrong_about'],
    promptAnswers: [
      'Defense will become the most consequential dual-use category of the decade.',
      'Israeli cyber is not a moat anymore — execution and US GTM are.',
    ],
  },
  {
    email: 'ravi.test@businesstinder.test',
    fullName: 'Ravi Krishnan',
    headline: 'Founder · voice AI for Indian SMB customer support',
    userType: 'founder',
    stage: 'live',
    industries: ['AI', 'B2B SaaS'],
    skills: ['Engineering', 'Product'],
    location: 'Bangalore',
    remoteOk: true,
    lookingFor: ['investors', 'customers'],
    bio: 'Multilingual voice agents handling 12 Indian languages. 30 mid-market customers, 2× growth quarterly.',
    commitment: 'full_time',
    pastCompanies: ['Freshworks', 'Razorpay'],
    promptIds: ['shipped', 'first_pilot'],
    promptAnswers: [
      'A Tamil/Hindi switching model that fooled our QA team in blind tests.',
      'Any D2C brand with 50k+ monthly support contacts.',
    ],
  },
  {
    email: 'sophie.test@businesstinder.test',
    fullName: 'Sophie Laurent',
    headline: 'Advisor · DTC consumer & luxury brand operators',
    userType: 'advisor',
    stage: 'scaling',
    industries: ['Consumer', 'Retail'],
    skills: ['Marketing', 'Domain expert'],
    location: 'Paris',
    remoteOk: true,
    lookingFor: ['advisors', 'partnerships'],
    bio: 'Built three 9-figure DTC brands. Advise on brand, CAC, and EU expansion. 1–2 hrs/month, equity-only.',
    commitment: 'part_time',
    pastCompanies: ['Sézane', 'Glossier'],
    promptIds: ['dream_advisor', 'wrong_about'],
    promptAnswers: [
      'Someone who has had to fire a beloved CMO. I can help you avoid that.',
      'Influencer CAC is not your acquisition strategy — it\'s your tax.',
    ],
  },
  {
    email: 'marcus.test@businesstinder.test',
    fullName: 'Marcus Andersson',
    headline: 'Climate-tech engineer seeking commercial co-founder',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['Climate', 'Hardware'],
    skills: ['Engineering'],
    location: 'Stockholm',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'PhD in electrochemistry. Have a working prototype for grid-scale iron-air storage. Need someone who knows how to sell to utilities.',
    commitment: 'full_time',
    pastCompanies: ['Northvolt', 'Vattenfall'],
    promptIds: ['building', 'skill_to_hire'],
    promptAnswers: [
      'Long-duration battery storage that\'s cheaper per kWh than lithium.',
      'A BD lead who has actually closed a utility deal.',
    ],
  },
  {
    email: 'layla.test@businesstinder.test',
    fullName: 'Layla Hassan',
    headline: 'Marketplace founder · $4M ARR, GCC region',
    userType: 'founder',
    stage: 'revenue',
    industries: ['Marketplace', 'B2B SaaS'],
    skills: ['Product', 'Sales'],
    location: 'Dubai',
    remoteOk: false,
    lookingFor: ['investors', 'partnerships'],
    bio: 'B2B wholesale marketplace for restaurants in UAE/KSA. Profitable, doubling YoY, raising Series A.',
    commitment: 'full_time',
    pastCompanies: ['Careem', 'Talabat'],
    promptIds: ['one_year_plan', 'biggest_open_question'],
    promptAnswers: [
      'Cross $10M ARR and open in Riyadh and Cairo.',
      'How fast can we add embedded finance without slowing core growth?',
    ],
  },
  {
    email: 'diego.test@businesstinder.test',
    fullName: 'Diego Romero',
    headline: 'Growth operator · ex-Revolut Spain GM',
    userType: 'operator',
    stage: 'scaling',
    industries: ['FinTech', 'Consumer'],
    skills: ['Marketing', 'Ops'],
    location: 'Madrid',
    remoteOk: true,
    lookingFor: ['cofounder', 'networking'],
    bio: 'Scaled Revolut Spain from 50k to 2M users. Open to founding GTM or a country GM role at a Series B fintech.',
    commitment: 'full_time',
    pastCompanies: ['Revolut', 'N26'],
    promptIds: ['shipped', 'best_with'],
    promptAnswers: [
      'A referral campaign that did 38% of Revolut Spain\'s 2022 acquisition.',
      'People who treat growth as a craft, not a hack.',
    ],
  },
  {
    email: 'kenji.test@businesstinder.test',
    fullName: 'Kenji Mori',
    headline: 'Principal @ HanArc Capital · gaming & creator economy',
    userType: 'investor',
    stage: 'scaling',
    industries: ['Gaming', 'Consumer'],
    skills: ['Capital'],
    location: 'Seoul',
    remoteOk: true,
    lookingFor: ['networking'],
    bio: 'Seed–Series B in gaming studios, creator tools, and virtual goods. APAC focus. $1–5M checks.',
    commitment: 'part_time',
    pastCompanies: ['Nexon', 'Krafton'],
    promptIds: ['industry_bet'],
    promptAnswers: ['Mid-budget original IP will beat AAA franchises for the next five years.'],
  },
  {
    email: 'olivia.test@businesstinder.test',
    fullName: 'Olivia Martin',
    headline: 'BioTech founder · synthetic biology for industrial enzymes',
    userType: 'founder',
    stage: 'mvp',
    industries: ['BioTech', 'Climate'],
    skills: ['Engineering', 'Domain expert'],
    location: 'Toronto',
    remoteOk: false,
    lookingFor: ['investors', 'advisors'],
    bio: 'Engineered enzymes that replace petrochemical catalysts at 40% lower cost. Pilot with a Tier-1 chemicals customer.',
    commitment: 'full_time',
    pastCompanies: ['Ginkgo Bioworks'],
    promptIds: ['dream_advisor', 'first_pilot'],
    promptAnswers: [
      'A former chemicals BD who has run plant trials in Europe.',
      'A specialty chemicals firm willing to co-fund a 6-month pilot.',
    ],
  },
  {
    email: 'wei.test@businesstinder.test',
    fullName: 'Wei Liu',
    headline: 'Cross-border FinTech founder · $8M ARR, hiring CFO',
    userType: 'founder',
    stage: 'scaling',
    industries: ['FinTech'],
    skills: ['Product', 'Engineering'],
    location: 'Hong Kong',
    remoteOk: true,
    lookingFor: ['hires', 'investors'],
    bio: 'Multi-currency accounts for HK/SG SMBs trading with mainland China. Profitable, prepping Series B.',
    commitment: 'full_time',
    pastCompanies: ['Airwallex'],
    promptIds: ['skill_to_hire', 'biggest_open_question'],
    promptAnswers: [
      'A CFO who has taken a fintech through MAS and HKMA scrutiny.',
      'When to expand to Indonesia — sooner with less capital, or later with more?',
    ],
  },
  {
    email: 'aaron.test@businesstinder.test',
    fullName: 'Aaron Brooks',
    headline: 'Looking for a technical co-founder · vertical AI for legal',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['B2B SaaS', 'AI'],
    skills: ['Sales', 'Domain expert'],
    location: 'Austin',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'Ex-corporate lawyer. Have 4 mid-market firms ready to pay if I can build the product. Need a technical co-founder.',
    commitment: 'full_time',
    pastCompanies: ['Latham & Watkins'],
    promptIds: ['building', 'first_pilot'],
    promptAnswers: [
      'AI that drafts and redlines contracts the way a senior associate would.',
      'Any 50–200 attorney firm doing M&A or commercial work.',
    ],
  },
  {
    email: 'nadia.test@businesstinder.test',
    fullName: 'Nadia Karim',
    headline: 'Climate-tech founder · regenerative ag for East Africa',
    userType: 'founder',
    stage: 'mvp',
    industries: ['AgriTech', 'Climate'],
    skills: ['Domain expert', 'Ops'],
    location: 'Nairobi',
    remoteOk: false,
    lookingFor: ['investors', 'partnerships'],
    bio: 'Carbon credits + yield uplift for smallholder farmers in Kenya and Uganda. 14,000 farmers, first credit issuance Q3.',
    commitment: 'full_time',
    pastCompanies: ['One Acre Fund'],
    promptIds: ['learned_hard_way', 'wrong_about'],
    promptAnswers: [
      'Carbon buyers care about MRV rigor 100× more than story.',
      'Smallholder ag is not charity — it\'s the most undercapitalized supply chain on earth.',
    ],
  },
  {
    email: 'erik.test@businesstinder.test',
    fullName: 'Erik Holm',
    headline: 'Hardware advisor · ex-Bang & Olufsen, ex-Apple ID',
    userType: 'advisor',
    stage: 'scaling',
    industries: ['Hardware', 'Consumer'],
    skills: ['Design', 'Domain expert'],
    location: 'Copenhagen',
    remoteOk: true,
    lookingFor: ['advisors', 'networking'],
    bio: 'Shipped 11 consumer hardware products. Advise founders on industrial design, supply chain, and EU manufacturing.',
    commitment: 'part_time',
    pastCompanies: ['Apple', 'Bang & Olufsen'],
    promptIds: ['learned_hard_way'],
    promptAnswers: ['Tooling cost is a lie until you\'ve done v2 — always budget for it.'],
  },
  {
    email: 'mei.test@businesstinder.test',
    fullName: 'Mei Chen',
    headline: 'Consumer founder · skincare brand, $3M GMV in 14 months',
    userType: 'founder',
    stage: 'live',
    industries: ['Consumer', 'Retail'],
    skills: ['Marketing', 'Product'],
    location: 'Shanghai',
    remoteOk: false,
    lookingFor: ['investors', 'partnerships'],
    bio: 'Clean skincare brand built on Xiaohongshu. 200k+ followers, 40% repeat rate. Expanding to SEA.',
    commitment: 'full_time',
    pastCompanies: ['L\'Oréal', 'Perfect Diary'],
    promptIds: ['shipped', 'one_year_plan'],
    promptAnswers: [
      'A launch campaign that did $500k GMV in the first 48 hours.',
      'Be the #1 indie clean-skincare brand in Southeast Asia.',
    ],
  },
  {
    email: 'carlos.test@businesstinder.test',
    fullName: 'Carlos Mendoza',
    headline: 'PropTech founder · short-term rental ops platform',
    userType: 'founder',
    stage: 'revenue',
    industries: ['PropTech', 'B2B SaaS'],
    skills: ['Product', 'Sales'],
    location: 'Miami',
    remoteOk: true,
    lookingFor: ['hires', 'customers'],
    bio: 'All-in-one ops stack for Airbnb property managers. 220 customers, $1.8M ARR, growing 15%/mo.',
    commitment: 'full_time',
    pastCompanies: ['Sonder', 'Vacasa'],
    promptIds: ['skill_to_hire', 'side_obsession'],
    promptAnswers: [
      'A head of customer success who has scaled a SMB SaaS through churn season.',
      'Restoring a 1972 Ford Bronco one weekend at a time.',
    ],
  },
  {
    email: 'tara.test@businesstinder.test',
    fullName: 'Tara Nguyen',
    headline: 'Founder · creator-economy SaaS, hiring head of growth',
    userType: 'founder',
    stage: 'revenue',
    industries: ['Consumer', 'B2B SaaS'],
    skills: ['Product', 'Marketing'],
    location: 'Sydney',
    remoteOk: true,
    lookingFor: ['hires', 'investors'],
    bio: 'Course-hosting platform for creators in APAC. 12,000 creators, $2.4M ARR, bootstrapped to date.',
    commitment: 'full_time',
    pastCompanies: ['Canva', 'Atlassian'],
    promptIds: ['one_year_plan', 'best_with'],
    promptAnswers: [
      'Cross $5M ARR and decide between bootstrapping further or raising.',
      'Operators who would rather ship a small thing today than plan a big thing for Q3.',
    ],
  },
];
