// Demo / test fixtures. The /admin/seed-fakes endpoint creates these as
// real User + Profile rows so the admin can swipe on a varied deck during
// testing. The cast covers every userType, several stages, and locations
// spread across continents so distance/geo filters can be exercised.

export const FAKE_PASSWORD = 'test1234';

export const FAKE_USERS = [
  {
    email: 'avery.test@businesstinder.test',
    fullName: 'Avery Chen',
    headline: 'Technical co-founder, ex-Stripe',
    userType: 'cofounder_search',
    stage: 'mvp',
    industries: ['AI', 'DevTools'],
    skills: ['Engineering', 'Product'],
    location: 'San Francisco',
    remoteOk: true,
    lookingFor: ['cofounder', 'investors'],
    bio: 'Building AI-native dev tooling. Looking for a hustler co-founder to balance my engineering depth.',
    commitment: 'full_time',
    pastCompanies: ['Stripe', 'Anthropic'],
    promptIds: ['building', 'best_with'],
    promptAnswers: [
      'A coding agent that pairs with you live in your editor.',
      'People who ship before they polish.',
    ],
  },
  {
    email: 'jamie.test@businesstinder.test',
    fullName: 'Jamie Rivera',
    headline: 'Solo founder · FinTech for LATAM',
    userType: 'founder',
    stage: 'live',
    industries: ['FinTech'],
    skills: ['Product', 'Domain expert'],
    location: 'Mexico City',
    remoteOk: false,
    lookingFor: ['hires', 'investors'],
    bio: 'Building remittance rails for the Mexico–US corridor. $40k MRR, growing 20%/mo.',
    commitment: 'full_time',
    pastCompanies: ['Kavak'],
    promptIds: ['first_pilot', 'one_year_plan'],
    promptAnswers: [
      'Any LATAM gig worker network with weekly USD payouts.',
      'Cross $1M ARR and close a $3M seed round.',
    ],
  },
  {
    email: 'sam.test@businesstinder.test',
    fullName: 'Sam Park',
    headline: 'GP @ HiveCapital · pre-seed checks $100k–$500k',
    userType: 'investor',
    stage: 'scaling',
    industries: ['B2B SaaS', 'AI'],
    skills: ['Capital'],
    location: 'New York',
    remoteOk: true,
    lookingFor: ['networking'],
    bio: 'Pre-seed B2B SaaS and AI infra. Ex-VP product @ Datadog. Always happy to do office hours.',
    commitment: 'part_time',
    pastCompanies: ['Datadog'],
    promptIds: ['industry_bet'],
    promptAnswers: ['Most of the AI infra winners will be vertical, not horizontal.'],
  },
  {
    email: 'rohan.test@businesstinder.test',
    fullName: 'Rohan Patel',
    headline: 'Founding GTM hire, looking for a seed B2B SaaS to join',
    userType: 'operator',
    stage: 'idea',
    industries: ['B2B SaaS'],
    skills: ['Sales', 'Ops'],
    location: 'Berlin',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'Closed $8M ARR at Plausible. Want to join a B2B SaaS team as founding GTM and earn into the cap table.',
    commitment: 'full_time',
    pastCompanies: ['Plausible'],
    promptIds: ['skill_to_hire', 'shipped'],
    promptAnswers: [
      'A pricing analyst who lives in spreadsheets.',
      'A self-serve onboarding flow that 5×ʼd Plausible activations.',
    ],
  },
  {
    email: 'maya.test@businesstinder.test',
    fullName: 'Maya Singh',
    headline: 'Designer-founder · consumer health',
    userType: 'founder',
    stage: 'mvp',
    industries: ['HealthTech', 'Consumer'],
    skills: ['Design', 'Product'],
    location: 'London',
    remoteOk: true,
    lookingFor: ['cofounder', 'advisors'],
    bio: 'Reimagining women\'s health from the ground up. Need a clinical co-founder.',
    commitment: 'full_time',
    pastCompanies: ['Babylon Health'],
    promptIds: ['wrong_about', 'dream_advisor'],
    promptAnswers: [
      'Consumer health is not won by another tracking app.',
      'A clinician who has run their own pilot.',
    ],
  },
  {
    email: 'dom.test@businesstinder.test',
    fullName: 'Dom Hartmann',
    headline: 'Climate-tech advisor · ex-Tesla supply chain',
    userType: 'advisor',
    stage: 'scaling',
    industries: ['Climate'],
    skills: ['Domain expert', 'Ops'],
    location: 'Berlin',
    remoteOk: true,
    lookingFor: ['networking', 'partnerships'],
    bio: 'Advising climate-tech founders on hardware supply chain. 12 years inside Tesla & Northvolt.',
    commitment: 'part_time',
    pastCompanies: ['Tesla', 'Northvolt'],
    promptIds: ['learned_hard_way'],
    promptAnswers: ['Battery factories are 10× harder than the spreadsheet says.'],
  },
  {
    email: 'ying.test@businesstinder.test',
    fullName: 'Ying Zhao',
    headline: 'Marketplace founder · $1.2M ARR, hiring head of growth',
    userType: 'founder',
    stage: 'revenue',
    industries: ['Marketplace', 'Consumer'],
    skills: ['Product', 'Marketing'],
    location: 'Singapore',
    remoteOk: false,
    lookingFor: ['hires', 'partnerships'],
    bio: 'Two-sided marketplace for tutoring in SEA. $1.2M ARR, 18 months in.',
    commitment: 'full_time',
    pastCompanies: ['Grab', 'Lazada'],
    promptIds: ['biggest_open_question'],
    promptAnswers: ['How do we move from one-region dominance to two without losing the unit economics?'],
  },
  {
    email: 'noah.test@businesstinder.test',
    fullName: 'Noah Williams',
    headline: 'Web3 builder · DeFi infra · ex-OpenSea',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['Web3'],
    skills: ['Engineering'],
    location: 'Lisbon',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'Solidity dev. Looking for a non-tech co-founder with deep finance domain expertise.',
    commitment: 'full_time',
    pastCompanies: ['OpenSea'],
    promptIds: ['building'],
    promptAnswers: ['On-chain credit infrastructure for emerging-market lenders.'],
  },
  {
    email: 'priya.test@businesstinder.test',
    fullName: 'Priya Iyer',
    headline: 'PM/engineer hybrid, want to build AI agents for SMBs',
    userType: 'cofounder_search',
    stage: 'idea',
    industries: ['B2B SaaS', 'AI'],
    skills: ['Product', 'Engineering'],
    location: 'San Francisco',
    remoteOk: true,
    lookingFor: ['cofounder'],
    bio: 'PM-eng hybrid, last 4 years at Notion. Want a sales/marketing co-founder.',
    commitment: 'full_time',
    pastCompanies: ['Notion'],
    promptIds: ['one_year_plan', 'best_with'],
    promptAnswers: [
      'Have 50 paying SMBs on an AI agent for their workflows.',
      'People who do customer interviews on weekends.',
    ],
  },
  {
    email: 'lukas.test@businesstinder.test',
    fullName: 'Lukas Müller',
    headline: 'Solo founder, hiring founding engineer (Rust/Go)',
    userType: 'founder',
    stage: 'live',
    industries: ['DevTools', 'AI'],
    skills: ['Engineering'],
    location: 'Amsterdam',
    remoteOk: true,
    lookingFor: ['hires', 'customers'],
    bio: 'AI code-review tool. 50 paying teams. Looking for a founding engineer who lives in low-level code.',
    commitment: 'full_time',
    pastCompanies: ['JetBrains'],
    promptIds: ['shipped', 'side_obsession'],
    promptAnswers: [
      'A static analyzer that catches real bugs without flooding you with false positives.',
      'Trail running ultras.',
    ],
  },
];
